#! /bin/sh

case "$1" in
  rebuild)
	echo "Rebuilding po files" >&2
  	../../../../bin/i18ndude rebuild-pot --exclude rss.pt --pot locales/konferenz.content.pot --create konferenz.content .
	;;
  sync)
	echo "Syncing po files" >&2
	../../../../bin/i18ndude sync --pot locales/konferenz.content.pot locales/*/LC_MESSAGES/konferenz.content.po
	;;
  all)
	echo "Rebuilding po files" >&2
  	../../../../bin/i18ndude rebuild-pot --exclude rss.pt --pot locales/konferenz.content.pot --create konferenz.content .
	echo "Syncing po files" >&2
	../../../../bin/i18ndude sync --pot locales/konferenz.content.pot locales/*/LC_MESSAGES/konferenz.content.po
	;;
  *)
	echo "Usage: $0 rebuild|sync|all" >&2
	exit 3
	;;
esac